- name: Clone VM from template
  community.general.proxmox_kvm:
    api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
    api_user: "{{ lookup('env', 'PROXMOX_USERNAME') }}"
    api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    validate_certs: "no"
    state: present
    node: "{{ vm_template_node }}"
    clone: "{{ vm_template_name }}"
    full: "yes"
    name: "{{ k8s_hostname }}"
    storage: "{{ storage }}"
    timeout: 300
  delegate_to: localhost
  register: vm_id

- name: Sleep for 10 seconds to wait for VM creation
  ansible.builtin.wait_for:
    timeout: 10
  delegate_to: localhost

- name: Update cloned VM with chosen CPU and Memory values
  community.general.proxmox_kvm:
    node: "{{ vm_template_node }}"
    api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
    api_user: "{{ lookup('env', 'PROXMOX_USERNAME') }}"
    api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    name: "{{ k8s_hostname }}"
    agent: "enabled=1"
    cores: "{{ proxmox_cores }}"
    memory: "{{ proxmox_memory }}"
    update: "yes"

- name: Ensure VM {{ vm_id.vmid }} is on {{ proxmox_node }}
  community.general.proxmox_kvm:
    api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
    api_user: "{{ lookup('env', 'PROXMOX_USERNAME') }}"
    api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    vmid: "{{ vm_id.vmid }}"
    node: "{{ proxmox_node }}"
    migrate: true
    state: present
  delegate_to: localhost
  async: 3600
  poll: 15

- name: Sleep for 10 seconds to wait for migration:Then continue with play
  ansible.builtin.wait_for:
    timeout: 10
  delegate_to: localhost

- name: Start VM
  community.general.proxmox_kvm:
    api_host: "{{ lookup('env', 'PROXMOX_URL') }}"
    api_user: "{{ lookup('env', 'PROXMOX_USERNAME') }}"
    api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
    name: "{{ k8s_hostname }}"
    node: "{{ proxmox_node }}"
    state: started

