- name: Install qemu-guest-agent (Debian/Ubuntu)
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: yes
  delegate_to: "{{ machine_name }}.rmblau.com"
  become: yes
  become_user: root
  become_flags: 'su - root /bin/bash -c'
- name: start qemu-guest-agent service
  ansible.builtin.systemd_service:
    state: started
    name: qemu-guest-agent
  become: yes
  become_user: root
  become_method: sudo
  become_flags: 'su - root /bin/bash -c'

- name: Retrieve VM information including network status
  community.general.proxmox_vm_info:
    api_host: "{{ proxmox_host }}"
    api_user: "root@pam"
    api_password: "{{ proxmox_password }}"
    vmid: "{{ vm_id }}"
    network: true
  register: vm_info
  delegate_to: localhost

- name: Display IP addresses
  debug:
    msg: |
      {% for vm in vm_info.proxmox_vms %}
      VM Name: {{ vm.name }}
        Hardware Address: {{ vm.network[1]['hardware-address'] }}
        {% for ip_address_info in vm.network[1]['ip-addresses'] %}
          IP Address ({{ip_address_info['ip-address-type'] }}): {{ip_address_info['ip-address'] }}
        {% endfor %}
      {% endfor %}